### ISSUE TITLE
current build has no UI, cant make a new file or draw anything..

### ISSUE THREAD

**Issue by damian-666** [JanusTida/Tida.CAD#1]
this is a nifty project but im wondering if im missing something.  all the code seems there, im running the only exe, the launcher.

theres is not File or Tool ribbons..

**Comment by JanusTida** [comment]
I can't reproduce the problems you encountered ,even cleaned the files, vs2019(version 16.7.7) seems to have a bug, it doesn't build any files after I clean the folder and click build.
can you tell me more about the details?
here is the file list that has been built.
![image](https://user-images.githubusercontent.com/29449156/97401727-4c0b5a80-192c-11eb-858e-d8cdd6f51c71.png)
