### ISSUE TITLE
Project license is missing

### ISSUE THREAD

**Issue by jcbeppler** [JanusTida/Tida.CAD#2]
Hello!

Nice project! I think you just forgot to include your license model for it, then you will probably attract more collaborators to help you.

Cheers!

**Comment by JanusTida** [comment]
Thanks for your tips,I've chosen MIT  as the project license,and I'll contribute to run this project,in next version I'll make the project come with less dependencies

**Comment by jcbeppler** [comment]
Amazing! I plan to start learning about it soon and maybe I can collaborate with some new features. 
Also, there's the new Windows App SDK, probably it is not so complex to migrate and you may get some cool new features for it!
